### ISSUE TITLE
Doesn't allow nested revisions directory

### ISSUE THREAD

**Issue by kevlarr** [kevlarr/jrny#28]
Given a structure like...

```
database/
└── revisions/
    └── ...files
jrny.toml
jrny-env.toml
```

... and a `jrny.toml` file like...

```toml
[revisions]
directory = "database/revisions"

[table]
schema = "jrny"
name = "revisions"
```

... trying to use any `jrny` command from the same directory as the config & env files results in an error like...

```
Error: `jrny-env.toml` must exist within same directory as config file or `--database-url` must be provided
```
